stages:
  - fast_checks
  - build
  - test
  - code_coverage
  - release

before_script:
  - ci-scripts/install-deps.sh

# Running fast-checks to notice an author that his pull-request fails our standatds.
# This checks should not produce any artifacts
fast_checks:
  stage: fast_checks
  script:
    - rustup component add rustfmt
    - cargo install cargo-audit
    - cargo audit
    - cargo fmt --all -- --check
  tags:
    - linux
  image: rust:1.32

.build:
  stage: build
  script:
    - cargo build
  artifacts:
    expire_in: 1 week
    paths:
      - target/
  dependencies:
    - fast_checks

build:linux:
  extends: .build
  image: rust:1.32
  tags:
    - linux

build:macos:
  extends: .build
  tags:
    - macos

.test:
  stage: test
  script:
    - cargo test --all -- --nocapture
  artifacts:
    expire_in: 1 week
    paths:
      - target/

test:linux:
  extends: .test
  image: rust:1.32
  dependencies:
    - build:linux
  tags:
    - linux

test:macos:
  extends: .test
  dependencies:
    - build:macos
  tags:
    - macos

code_coverage:
  stage: code_coverage
  image: rust:1.32
  before_script:
  script:
    - ci-scripts/coverage.sh
  dependencies:
    - test:linux
  tags:
    - linux
  only:
    - dev
    - master

.release:
  stage: release
  only:
    - dev
    - master
  when: manual
  dependencies: []
  artifacts:
    expire_in: 1 week
    paths:
      - release/

release:linux:
  extends: .release
  image: rust:1.32
  script:
    - cargo install --path . --root /usr/local && strip /usr/local/bin/stegos
    - mkdir -p release/linux && mv /usr/local/bin/stegos release/linux
  tags:
    - linux

release:macos:
  extends: .release
  script:
    - sudo cargo install --path . --root /usr/local && sudo strip /usr/local/bin/stegos
    - mkdir -p release/macos && mv /usr/local/bin/stegos release/macos
  tags:
    - macos

