stages:
  - fast_checks
  - build
  - test
  - code_coverage
  - release

before_script:
  - ci-scripts/install-deps.sh
  - rustup component add rustfmt
  - cargo install cargo-audit

# Running fast-checks to notice an author that his pull-request fails our standatds.
# This checks should not produce any artifacts
fast_checks:
  stage: fast_checks
  script:
    - cargo audit
    - cargo fmt --all -- --check
  tags:
    - linux
  image: rust:1.32

.build:
  stage: build
  script:
    - cargo build
  artifacts:
    expire_in: 1 week
    paths:
      - target/
  dependencies:
    - fast_checks

build:linux:
  extends: .build
  image: rust:1.32
  tags:
    - linux

build:macos:
  extends: .build
  tags:
    - macos

.test:
  stage: test
  script:
    - RUST_MIN_STACK=8388608 cargo test --all -- --nocapture
  artifacts:
    expire_in: 1 week
    paths:
      - target/

test:linux:
  extends: .test
  image: rust:1.32
  dependencies:
    - build:linux
  tags:
    - linux

test:macos:
  extends: .test
  dependencies:
    - build:macos
  tags:
    - macos

code_coverage:
  stage: code_coverage
  image: rust:1.32
  script:
    - ci-scripts/coverage.sh
  dependencies:
    - test:linux
  tags:
    - linux
  only:
    - dev
    - master

.release:
  stage: release
  script:
    - cargo build --release
  only:
    - dev
    - master
  when: manual
  artifacts:
    expire_in: 1 week
    paths:
      - target/

release:linux:
  extends: .release
  image: rust:1.32
  tags:
    - linux

release:macos:
  extends: .release
  tags:
    - macos
