stages:
  - build
  - test
  - code_coverage
  - release

before_script:
  - ci-scripts/install-deps.sh
  - rustup component add rustfmt
.build:
  stage: build
  script:
    - cargo build
  artifacts:
    expire_in: 1 week
    paths:
      - target/

build:linux:
  extends: .build
  image: rust:1.32
  tags:
    - linux

.test:
  stage: test
  script:
    - cargo test --all -- --nocapture
    - cargo fmt --all -- --check
  artifacts:
    expire_in: 1 week
    paths:
      - target/

test:linux:
  extends: .test
  image: rust:1.32
  dependencies:
    - build:linux
  tags:
    - linux

code_coverage:
  stage: code_coverage
  image: rust:1.32
  script:
    - ci-scripts/coverage.sh
  dependencies:
    - test:linux
  tags:
    - linux
  only:
    - dev
    - master

.release:
  stage: release
  script:
    - cargo build --release
  only:
    - dev
    - master
  when: manual
  artifacts:
    expire_in: 1 week
    paths:
      - target/

release:linux:
  extends: .release
  image: rust:1.32
  tags:
    - linux

