stages:
  - build
  - test
  - release

before_script:
  - ci-scripts/install-deps.sh
.build: &build_definition
  stage: build
  script:
    - cargo build
  artifacts:
    expire_in: 1 week
    paths:
      - target/

build:linux:
  image: rust:1.29
  <<: *build_definition
  tags:
    - linux

.test: &test_definition
  stage: test
  script:
    - cargo test

test:linux:
  image: rust:1.29
  <<: *test_definition
  dependencies:
    - build:linux
  tags:
    - linux

.release: &release_definition
  stage: release
  script:
    - cargo build --release
  only:
    - dev
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - target/

release:linux:
  image: rust:1.29
  <<: *release_definition
  tags:
    - linux
