[package]
name = "stegos_network"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]

[dependencies]
stegos_config = { path = "../config" }
bytes = "0.4.10"
failure = "0.1.2"
failure_derive = "0.1.2"
futures = "0.1.25"
slog = "~2.4"
tokio = "0.1.11"
rand = "0.5.5"
fnv = "1.0.6"
parking_lot = "0.6.4"
tokio-codec = "0.1.1"
protobuf = "2.1.2"
unsigned-varint = "0.2.1"
tokio-io = "0.1.9"
tokio-stdin = "0.1.1"
tokio-current-thread = "0.1.3"

libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "e179951c74cb0c8916d27329f2dfd78917dddfb2" }
