[package]
name = "stegos_network"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]
build = "build.rs"

[dependencies]
bytes = "0.4"
failure = "0.1"
failure_derive = "0.1"
fnv = "1.0"
futures = "0.1"
ipnetwork = "^0.12"
log = "0.4"
pnet = "0.21"
parking_lot = "0.6"
protobuf = "2.1"
rand = "0.6"
stegos_config = { path = "../config" }
stegos_keychain = { path = "../keychain" }
stegos_crypto = { path = "../crypto" }
tokio = "0.1"
tokio-codec = "0.1"
tokio-current-thread = "0.1"
tokio-io = "0.1"
tokio-stdin = "0.1"
unsigned-varint = "0.2"

libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "e179951c74cb0c8916d27329f2dfd78917dddfb2" }

[dev-dependencies]
simple_logger = "1.0"
env_logger = "0.6"

[build-dependencies]
# protoc-rust = "2.1"
protobuf-codegen-pure = "2.1"

[[example]]
name = "floodsub"

[[example]]
name = "muxedsub"

[[example]]
name = "echo-server"

[[example]]
name = "echo-dialer"

[[example]]
name = "ncp-ping"
