[package]
name = "stegos_blockchain"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.com>"]
edition = "2018"
links = "stegos_blockchain"
build = "build.rs"

[dependencies]
stegos_keychain = { path = "../keychain" }
stegos_crypto = { path = "../crypto" }
stegos_serialization = {path = "../serialization"}
rocksdb = "0.11.0"
byteorder = "1.3.1"
tokio-timer = "0.2"
chrono = "0.4"
rand = "0.6"
log = "0.4"
failure = "0.1"
bitvector = "0.1"
protobuf = "2.2"
tempdir = "0.3"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
simple_logger = "1.0"

[build-dependencies]
stegos_serialization = {path = "../serialization"}