[package]
name = "stegos_consensus"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]
edition = "2018"

[dependencies]
log = "0.4"
failure = "0.1"
stegos_crypto = { path = "../crypto" }
stegos_blockchain = { path = "../blockchain" }
bitvector = "0.1"