[package]
name = "stegos_randhound"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]

[dependencies]
stegos_crypto = { path = "../crypto" }
stegos_network = { path = "../network" }
generic-array = "0.12.0"
hex = "0.3.2"
lazy_static = "1.1.0"
parking_lot = "0.6.4"
rand = "0.5"
typenum = "1.10.0"
futures = "0.1.25"
tokio = "0.1.11"
tokio-timer = "0.2.7"
failure = "0.1.2"
failure_derive = "0.1.2"
log = "0.4"