[general]
log4rs_config = "stegos-log4rs.toml"

[keychain]
private_key = "testing/node01/stegos.skey"
public_key = "testing/node01/stegos.pkey"
pbc_pkey = "testing/node01/stegos-pbc.pkey"

[network]
### default = "0.0.0.0"
# bind_ip = "127.0.0.1"
node_id = "node01"
bind_port = 10055
advetise_local_ips = false
broadcast_topic = "chat"
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10055",
]
