[package]
name = "stegos_crypto"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]

[dependencies]
generic-array = "0.12.0"
hex = "0.3.2"
lazy_static = "1.1.0"
parking_lot = "0.6.4"
rand = "0.5"
rust-crypto = "0.2.36"
rust-gmp = "0.5.0"
rust-libpbc = { git = "https://github.com/stegos/rust-pbcintf.git" }
sha3 = "0.8.0"
typenum = "1.10.0"
log = "0.4"